### ISSUE TITLE
Link to CMSIS-DAP firmware

### ISSUE THREAD

**Issue by GiedriusM** [8devices/lwm2m-client-rtl8710#1]
README states 

> Most RTL8710 based development boards include a CMSIS-DAP interface for device flashing and debugging, so proper driver installation might be needed.

Link to page with download and installation info should be provided.
Note: provided CMSIS-DAP firmware should have properly working virtual COM port AND fast firmware upload.

**Comment by taubel** [comment]
Readme now provides link for DAP firmware download and installation
